export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const RECEIVED_FRIEND_REQUEST_LIST = 'RECEIVED_FRIEND_REQUEST_LIST';
export const SEND_FRIEND_REQUEST_LIST = 'SEND_FRIEND_REQUEST_LIST';
export const ACCEPT_DENIED_PROFILE = 'ACCEPT_DENIED_PROFILE';
