export const REGISTER_USER = 'REGISTER_USER';
export const FETCH_ZODIC_SIGN = 'FETCH_ZODIC_SIGN';
export const FETCH_AUSPICIOUS_DROPDOWN = 'FETCH_AUSPICIOUS_DROPDOWN';
export const FETCH_MARITALSTATUS_DROPDOWN = 'FETCH_MARITALSTATUS_DROPDOWN';
export const FETCH_EDUCATION_DROPDOWN = 'FETCH_EDUCATION_DROPDOWN';
export const FETCH_JOB_DROPDOWN = 'FETCH_JOB_DROPDOWN';
export const VERIFY_USER = 'VERIFY_USER';
export const FETCH_PROFILECREATER_DROPDOWN = 'FETCH_PROFILECREATER_DROPDOWN';

export const FETCH_COUNTRY_DROPDOWN = 'FETCH_COUNTRY_DROPDOWN';
export const FETCH_STATE_DROPDOWN = 'FETCH_STATE_DROPDOWN';
export const FETCH_CITY_DROPDOWN = 'FETCH_CITY_DROPDOWN';
export const FETCH_GOTRA_DROPDOWN = 'FETCH_GOTRA_DROPDOWN';
export const FETCH_LAND_DROPDOWN = 'FETCH_GOTRA_DROPDOWN';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

