import {createSlice} from '@reduxjs/toolkit';

const initialState = {
  othersProfileData: {
    userSignupType: '',
    userUserName: '',
    userFirstName: '',
    userLastName: '',
    userEmail: '',
    userMobileNo: '',
    userDob: '',
    userGender: '',
    userProfileCreatedBy: {
      profileCreatedByNameHi: '',
      profileCreatedByNameEn: '',
      profileCreatedByStatus: '',
      profileCreatedById: 0,
      profileCreatedByCreatedAt: '',
      profileCreatedByUpdatedAt: '',
    },
    userCountry: {
      countryShortName: '',
      countryName: '',
      countryPhoneCode: '',
      countryStatus: '',
      countryId: 0,
      countryCreatedAt: '',
      countryUpdatedAt: '',
    },
    userState: {
      name: '',
      countryId: 0,
      stateStatus: '',
      stateId: '',
      stateCreatedAt: '',
      stateUpdatedAt: '',
    },
    userCity: {
      cityName: '',
      cityStateId: 0,
      cityStatus: '',
      cityId: '',
      cityCreatedAt: '',
      cityUpdatedAt: '',
    },
   // userTown: 'null',
    userReligiousInfo: {
      userReligiousInfoTimeOfBirth: '',
      userReligiousInfoPlaceOfBirth: '',
      userReligiousInfoGotra: {
        gotraTitleHi: '',
        gotraTitleEn: '',
        gotraStatus: '',
        gotraId: 0,
        //gotraCreatedAt: 'null',
        //gotraUpdatedAt: 'null',
      },
     // userReligiousInfoSubCaste: 'null',
    //  userReligiousInfoMotherTongue: 'null',
      userReligiousInfoZodiac: {
        zodiacTitleHi: ' ',
        zodiacTitleEn: '',
        zodiacStatus: '',
        zodiacId: 0,
        zodiacCreatedAt: ' ',
        zodiacUpdatedAt: ' ',
      },
      userReligiousInfoManglik: '',
      userReligiousInfoNakshatra: ' ',
      userReligiousInfoMotherGotra: '',
      userReligiousInfoId: 0,
      userReligiousInfoCreatedAt: '',
      userReligiousInfoUpdatedAt: '',
    },
    userContactInfo: {
      userContactInfoContactNo: '',
      userContactInfoWhatsappNo: '',
      userContactInfoPresentAddress: '',
      userContactInfoPermanentAddress: '',
      userContactInfoId: 0,
      userContactInfoCreatedAt: '',
      userContactInfoUpdatedAt: '',
    },
    userEducationInfo: {
      userEducationInfoEducation: {
        educationTitleHi: '',
        educationTitleEn: '',
        educationStatus: '',
        educationId: 0,
        educationCreatedAt: ' ',
        educationUpdatedAt: ' ',
      },
      userEducationInfoOccupation: {
        occupationTitleHi: '',
        occupationTitleEn: '',
        occupationStatus: '',
        occupationId: 0,
        occupationCreatedAt: ' ',
        occupationUpdatedAt: ' ',
      },
     // userEducationInfoProfession: 'null',
     // userEducationInfoOccupationDetails: 'null',
      //userEducationInfoAnnualIncome: 'null',
      userEducationInfoId: 0,
      userEducationInfoCreatedAt: '',
      userEducationInfoUpdatedAt: '',
    },
    userFamilyInfo: {
      userFamilyInfoFatherName: '',
      userFamilyInfoFatherOccupation: {
        occupationTitleHi: '',
        occupationTitleEn: '',
        occupationStatus: '',
        occupationId: 0,
        occupationCreatedAt: ' ',
        occupationUpdatedAt: ' ',
      },
      userFamilyInfoMotherName: '',
      userFamilyInfoMotherOccupation: ' ',
      userFamilyInfoNoOfMarriedBrothers: '',
      userFamilyInfoNoOfUnmarriedBrothers: '',
      userFamilyInfoNoOfMarriedSisters: '',
      userFamilyInfoNoOfUnmarriedSisters: '',
      userFamilyInfoMaternalUnclesName: ' ',
      userFamilyInfoMaternalUnclesGotra: ' ',
      userFamilyInfoLand: 0,
      userFamilyInfoHouse: '',
      userFamilyInfoCar: '',
      userFamilyInfoMotherMaika: '',
      userFamilyInfoNoOfSister: '',
      userFamilyInfoNoOfBrother: '',
      userFamilyInfoId: 0,
      userFamilyInfoCreatedAt: '',
      userFamilyInfoUpdatedAt: '',
    },
    userPersonalInfo: {
      userPersonalInfoMaritalStatusId: {
        maritalStatusTitleHi: '',
        maritalStatusTitleEn: '',
        maritalStatusStatus: '',
        maritalStatusId: 0,
        maritalStatusCreatedAt: ' ',
        maritalStatusUpdatedAt: ' ',
      },
      //userPersonalInfoComplexion: 'null',
      userPersonalInfoHeight: 0,
      //userPersonalInfoWeight: 'null',
     // userPersonalInfoDiet: 'null',
      userPersonalInfoDisability: 0,
     // userPersonalInfoBloodGroup: 'null',
      userPersonalInfoId: 57,
      userPersonalInfoCreatedAt: '',
      userPersonalInfoUpdatedAt: '',
    },
    //userPartnerPreference: 'null',
    userIsVisible: '',
    userIsActive: '',
  //  userProfileImage: 'null',
    userId: 0,
    userCreatedAt: '',
    userUpdatedAt: '',
    userAge: '',
  },
};

const searchProfileSlice = createSlice({
  name: 'othersDetail',
  initialState,
  reducers: {
    fetchothersProfileData(state, action) {
      state.othersProfileData = action.payload;
    },
  },
});

const {actions, reducer} = searchProfileSlice;

export const {fetchothersProfileData} = actions;
export default reducer;
